services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: local-test
      MYSQL_ROOT_PASSWORD: test
      TZ: Asia/Seoul
    ports:
      - 13306:3306
    command: mysqld --sql_mode=""
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-net

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - 4572:4572
      - 4566:4566
    environment:
      - SERVICES=s3, sqs
    volumes:
      - "./localstack-init/init.sh:/etc/localstack/init/ready.d/init-aws.sh"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge