spring:
  config:
    import:
      - cloud.yml

---
spring.config.activate.on-profile: local-container

spring:
  cloud:
    aws:
      s3:
        region: us-east-1
        bucket: ai-blog-draft

---
spring.config.activate.on-profile: local

spring:
  cloud:
    aws:
      s3:
        region: us-east-1
        bucket: ai-blog-draft

---
spring.config.activate.on-profile: live

spring:
  cloud:
    aws:
      s3:
        region: ap-northeast-2
        bucket: draft-blog
