spring.application.name=image

---
spring.config.activate.on-profile: local-container

spring:
  cloud:
    aws:
      s3:
        region: us-east-1
        bucket: ai-blog-draft
      endpoint: localstack:4566

---
spring.config.activate.on-profile: local

spring:
  cloud:
    aws:
      s3:
        region: us-east-1
        bucket: ai-blog-draft
      endpoint: http://127.0.0.1:4566

---
spring.config.activate.on-profile: live

spring:
  cloud:
    aws:
      s3:
        region: ap-northeast-2
        bucket: draft-blog
