spring:
  config:
    import:
      - cloud.yml

---
spring.config.activate.on-profile: local-container

spring:
  cloud:
    aws:
      sqs:
        region: us-east-1

---
spring.config.activate.on-profile: local

spring:
  cloud:
    aws:
      sqs:
        region: us-east-1

---
spring.config.activate.on-profile: live

spring:
  cloud:
    aws:
      sqs:
        region: ap-northeast-2
