spring.application.name=storage

---
spring.config.activate.on-profile: local-container

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/local-test
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/local-test
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring.config.activate.on-profile: live

spring:
  datasource:
    url: ${AWS_RDS_URL}
    username: ${AWS_RDS_USERNAME}
    password: ${AWS_RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
