### 초안 요청 키 획득
POST localhost:8080/v1/drafts/temp
Content-Type: application/json

{
  "userId": 1
}

### 초안 상태 조회
GET localhost:8080/v1/drafts/status?userId=1
Content-Type: application/json

### 초안 조회
GET localhost:8080/v1/drafts/1?userId=1
Content-Type: application/json
